#resolver: nightly-2020-09-05
resolver: lts-16.6
extra-deps:
  - algebra-4.3.1

  - hasql-th-0.4.0.8
  - telegram-bot-simple-0.3.1

  - postgresql-syntax-0.3.0.3
  - servant-multipart-0.11.6

  - fast-builder-0.1.2.0
  - headed-megaparsec-0.2

  - megaparsec-9.0.0

allow-newer: true
packages:
- .
